version: '3'

x-app:
  &app
  build:
    context: .
    dockerfile: Dockerfile
    target: development
  tmpfs:
    - /tmp
  volumes:
    - .:/ror:cached
    - rails_cache:/ror/tmp/cache:delegated
  # depends_on:
  #   - db

services:
  # db:
  #   image: postgres:12-alpine
  #   volumes:
  #     - postgresql:/var/lib/postgresql/data:delegated
  #     # Uncomment to access this containers Postgres instance via port 5432
  #   ports:
  #     - "127.0.0.1:5432:5432"
  #   environment:
  #     PSQL_HISTFILE: /root/log/.psql_history
  #     POSTGRES_USER: monta
  #     POSTGRES_PASSWORD: monta
  #   restart: on-failure
  #   logging:
  #     driver: none
  #   container_name: "rb_db"
  web:
    <<: *app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # volumes:
    #   - .:/rb_web_volume:cached
    ports:
      - "127.0.0.1:3000:3000"
    # depends_on:
    #   - db
    container_name: "rb_web"

volumes:
  # postgresql:
  rails_cache:
